NAME	=	Aanimal
SRCS	=	main.cpp AAnimal.cpp Cat.cpp Dog.cpp WrongAnimal.cpp WrongCat.cpp Brain.cpp
OBJS	=	$(SRCS:.cpp=.o)
CC		=	c++
RM		=	rm -f
FLAGS	=	-Wall -Werror -Wextra -std=c++98


all: $(NAME)

$(NAME): $(OBJS)
		@$(CC) $(FLAGS) $(OBJS) -o $(NAME)

clean:
		@$(RM) $(OBJS)

fclean:	clean
		@$(RM) $(NAME)

re:	fclean all

.PHONY: all clean fclean re bonus
